# docker-compose build
version: '2.1'


services:
  db:
    image: postgres:15.2
    volumes:
      - ./dbdata:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: 'exit 0'
