enum TransactionType {
  Expense
  Income
}

enum Provider {
  Google
}

table category {
  id integer [pk, unique]
  title varchar [not null]
  icon_name varchar
  is_common_category bool
  owner_id integer [ref: > users.id ]
}

table users {
  id integer [pk, unique]
  email varchar [unique]
  provider Provider
  social_id varchar
  first_name varchar
  last_name varchar
}

table transactions {
  id integer [pk, unique]
  type TransactionType
  owner_id integer [ref: > users.id]
  category_id integer [ref: > category.id]
  amount decimal [not null]
  title varchar [not null]
  description varchar [not null]
  date timestamp [not null]
}
